[package]
name = "uwussh-desktop"
description = "UwUSSH desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "uwussh_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
uwussh-core.workspace = true
uwussh-import.workspace = true
uwussh-proto.workspace = true
uwussh-store.workspace = true
uwussh-sync.workspace = true
uwussh-vault.workspace = true

base64.workspace = true
minisign-verify = "0.2"
parking_lot.workspace = true
semver = "1"
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
zeroize.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
] }
