// The installer speaks like UwUSSH's default, playful tone, in German or English.

const de = {
  welcomeTitle: 'Hallo! Ich bin Nyu',
  welcomeBody: 'Ich richte UwUSSH in ein paar Sekunden auf deinem {computer} ein.',
  againTitle: 'Schön, dich wiederzusehen!',
  againBody:
    'UwUSSH {installed} ist schon da. Ich bringe es auf {version}, deine Hosts und dein Tresor bleiben, wo sie sind.',
  install: 'Installieren',
  update: 'Aktualisieren',
  reinstall: 'Neu installieren',
  options: 'Optionen',
  fewerOptions: 'Weniger Optionen',
  folder: 'Speicherort',
  change: 'Ändern …',
  desktopShortcut: 'Verknüpfung auf dem Desktop',
  keygen: 'UwUKeygen mitinstallieren (SSH-Schlüssel erzeugen)',
  runningTitle: 'UwUSSH ist gerade offen',
  runningBody:
    'Ich schließe es kurz, damit ich weitermachen kann. Offene Verbindungen werden dabei getrennt, und ein Key in UwUKeygen, der noch nicht gespeichert ist, geht verloren.',
  closeAndContinue: 'Schließen und weiter',
  back: 'Zurück',
  progressInstall: 'Nyu richtet alles ein …',
  progressUpdate: 'Nyu bringt UwUSSH auf den neuesten Stand …',
  progressUninstall: 'Nyu räumt auf …',
  quotes: [
    'Sortiert Schlüssel …',
    'Poliert die Prompts …',
    'Prüft Fingerprints …',
    'Wärmt die Tastatur vor …',
    'Übt Ohrenwackeln …',
    'Rollt Kabel auf …',
    'Zählt die Tabs …',
  ],
  doneTitle: 'Fertig! ✧',
  doneBody: 'UwUSSH ist bereit für deine Server.',
  updateDoneTitle: 'Alles frisch! ✧',
  updateDoneBody: 'UwUSSH {version} startet gleich wieder.',
  tipsTitle: 'Kleine Tipps',
  tips: [
    'Jede Verbindung bekommt ihren eigenen Tab, auch mehrere zum selben Server.',
    'Hosts schon in Termius, PuTTY, KiTTY oder ~/.ssh/config? Der Import holt sie rüber.',
    'Stabil oder Beta? Den Update-Kanal wählst du in den Einstellungen.',
  ],
  start: 'UwUSSH starten',
  close: 'Schließen',
  errorTitle: 'Hoppla, das hat nicht geklappt',
  retry: 'Nochmal versuchen',
  uninstallTitle: 'Schade, dass du gehst …',
  uninstallBody: 'Ich entferne UwUSSH von diesem {computer}.',
  removeInstead: 'Deinstallieren …',
  computerWindows: 'PC',
  computerMac: 'Mac',
  computerLinux: 'Rechner',
  keepData: 'Hosts, Tresor und Einstellungen behalten',
  keepDataHint:
    'Praktisch, falls du wiederkommst. Sonst lösche ich auch den Tresor mit allen gespeicherten Schlüsseln und Passwörtern.',
  uninstall: 'Deinstallieren',
  keep: 'Doch behalten',
  goodbyeTitle: 'Tschüss! (｡•́︿•̀｡)',
  goodbyeBody: 'UwUSSH ist entfernt. Komm gern wieder vorbei.',
  soundOn: 'Ton an',
  soundOff: 'Ton aus',
  minimize: 'Minimieren',
  devBuild: 'Entwicklungs-Build: UwUSSH ist hier nicht mit drin.',
  sandbox: 'Testmodus: Es wird nur in einem Testordner installiert.',
  footer: 'Version {version} · Open Source',
};

const en: typeof de = {
  welcomeTitle: "Hi! I'm Nyu",
  welcomeBody: "I'll set up UwUSSH on your {computer} in a few seconds.",
  againTitle: 'Nice to see you again!',
  againBody:
    "UwUSSH {installed} is already here. I'll bring it to {version}, and your hosts and vault stay where they are.",
  install: 'Install',
  update: 'Update',
  reinstall: 'Reinstall',
  options: 'Options',
  fewerOptions: 'Fewer options',
  folder: 'Location',
  change: 'Change …',
  desktopShortcut: 'Shortcut on the desktop',
  keygen: 'Also install UwUKeygen (make SSH keys)',
  runningTitle: 'UwUSSH is open right now',
  runningBody:
    "I'll close it for a moment so I can carry on. Open connections will be closed, and a key in UwUKeygen that isn't saved yet is lost.",
  closeAndContinue: 'Close and continue',
  back: 'Back',
  progressInstall: 'Nyu is setting everything up …',
  progressUpdate: 'Nyu is bringing UwUSSH up to date …',
  progressUninstall: 'Nyu is tidying up …',
  quotes: [
    'Sorting keys …',
    'Polishing prompts …',
    'Checking fingerprints …',
    'Warming up the keyboard …',
    'Practicing ear wiggles …',
    'Coiling cables …',
    'Counting tabs …',
  ],
  doneTitle: 'All done! ✧',
  doneBody: 'UwUSSH is ready for your servers.',
  updateDoneTitle: 'All fresh! ✧',
  updateDoneBody: 'UwUSSH {version} starts again in a moment.',
  tipsTitle: 'Little tips',
  tips: [
    'Every connection gets its own tab, several to the same server too.',
    'Hosts already in Termius, PuTTY, KiTTY or ~/.ssh/config? The import brings them over.',
    'Stable or Beta? Pick the update channel in the settings.',
  ],
  start: 'Start UwUSSH',
  close: 'Close',
  errorTitle: "Oops, that didn't work",
  retry: 'Try again',
  uninstallTitle: 'Sad to see you go …',
  uninstallBody: "I'll remove UwUSSH from this {computer}.",
  removeInstead: 'Uninstall …',
  computerWindows: 'PC',
  computerMac: 'Mac',
  computerLinux: 'computer',
  keepData: 'Keep hosts, vault and settings',
  keepDataHint:
    'Handy if you come back. Otherwise I also delete the vault with every saved key and password.',
  uninstall: 'Uninstall',
  keep: 'Keep it',
  goodbyeTitle: 'Bye! (｡•́︿•̀｡)',
  goodbyeBody: 'UwUSSH is removed. Come back any time.',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  minimize: 'Minimize',
  devBuild: "Development build: UwUSSH isn't packed inside.",
  sandbox: 'Test mode: installs into a test folder only.',
  footer: 'Version {version} · Open source',
};

export type Texts = typeof de;

export const texts: Texts = navigator.language.toLowerCase().startsWith('de') ? de : en;

export function fill(template: string, values: Record<string, string>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => values[key] ?? '');
}
